const caseStudiesData = [
  // Brand Collaborations
  { title: "European Diplomatic Meeting", description: "High-level diplomatic meeting with European embassies exploring cultural exchange through premium spirits.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/brand-collaborations/european-diplomatic-meeting.jpg", eventType: "Brand Collaboration", date: "May 2025", location: "Hong Kong", year: "2025" },
  { title: "Honney Conti XO Presentation", description: "Exclusive launch event featuring the premium XO cognac collection with master blender insights.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/brand-collaborations/honney-conti-xo-presentation.jpg", eventType: "Brand Collaboration", date: "April 2025", location: "Hong Kong", year: "2025" },
  { title: "Honney Conti Launch Event", description: "Celebration introducing Honney Conti to the Hong Kong premium spirits market.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/brand-collaborations/honney-conti-launch-event.jpg", eventType: "Brand Collaboration", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "Planet1 Cognac Partnership", description: "Strategic alliance signed between United Spirits and Planet1 for Asian market distribution.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/brand-collaborations/planet1-cognac-partnership.jpg", eventType: "Brand Collaboration", date: "February 2025", location: "Hong Kong", year: "2025" },

  // Diplomatic Visits
  { title: "Chile Ambassador Visit", description: "Formal visit by the Chilean Ambassador to United Spirits' Hong Kong headquarters.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/diplomatic-visits/chile-ambassador-arrival.jpg", eventType: "Diplomatic Visit", date: "May 2025", location: "Hong Kong", year: "2025" },
  { title: "Chile Embassy Wine Tasting", description: "Exclusive tasting event hosted at the Chilean Embassy featuring premium Chilean wines.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/diplomatic-visits/chile-ambassador-visit-hocha.jpg", eventType: "Diplomatic Visit", date: "April 2025", location: "Chilean Embassy, HK", year: "2025" },
  { title: "Spanish Trade Delegation", description: "Meeting with Spanish trade representatives to explore premium spirits opportunities.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/diplomatic-visits/chile-ambassador-visit-suediane.jpg", eventType: "Diplomatic Visit", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "Cultural Exchange Event", description: "International cultural exchange event at Manor Suedane featuring global premium spirits.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/manor-suedane.jpg", eventType: "Diplomatic Visit", date: "February 2025", location: "Manor Suedane, HK", year: "2025" },

  // Education Events
  { title: "The Art of Aged Whiskey", description: "Masterclass exploring the science and artistry behind whiskey maturation processes.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/beidu-wine-tasting-event.jpg", eventType: "Education Event", date: "June 2025", location: "Hong Kong", year: "2025" },
  { title: "Wine & Food Pairing Masterclass", description: "Guided session with Michelin-starred chef and sommelier on perfect wine and food combinations.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/bernard-magrez-wine-tasting.jpg", eventType: "Education Event", date: "May 2025", location: "Hong Kong", year: "2025" },
  { title: "Brandy Tasting 101", description: "Introductory workshop on Cognac and Armagnac production, aging, and evaluation techniques.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/honeyconti-brand-positioning-talk.jpg", eventType: "Education Event", date: "April 2025", location: "Hong Kong", year: "2025" },
  { title: "Scotch vs Bourbon", description: "Comparative tasting session exploring the distinctive characteristics of these two iconic whiskey styles.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/honeyconti-founder-keynote.jpg", eventType: "Education Event", date: "April 2025", location: "Hong Kong", year: "2025" },
  { title: "Vintage Wine Seminar", description: "In-depth seminar on identifying and appreciating vintage wines from renowned regions.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/honney-conti-strategic-partnership-event.jpg", eventType: "Education Event", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "Aging Spirits", description: "A behind-the-scenes look at how time and environment shape the character of fine spirits.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/honney-conti-warehouse-tour.jpg", eventType: "Education Event", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "Sommelier Workshop", description: "Professional training for aspiring sommeliers covering service, pairing, and certification.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/martian-wine-training.jpg", eventType: "Education Event", date: "February 2025", location: "Hong Kong", year: "2025" },
  { title: "Distillation Process", description: "Educational workshop demystifying the science and craft of spirit distillation.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/metro-wine-education-workshop.jpg", eventType: "Education Event", date: "January 2025", location: "Hong Kong", year: "2025" },
  { title: "Terroir & Taste", description: "Exploring how soil, climate, and tradition influence the unique flavor profiles of wines.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/wine-festival-presentation.jpg", eventType: "Education Event", date: "December 2024", location: "HK Wine & Spirits Festival", year: "2024" },
  { title: "Rare Spirits Panel", description: "Panel discussion with collectors and experts on sourcing and valuing rare and collectible spirits.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/education-events/wine-tasting-event.jpg", eventType: "Education Event", date: "November 2024", location: "Hong Kong", year: "2024" },

  // Facility Tours
  { title: "VIP Warehouse Tour", description: "Behind-the-scenes access to our temperature-controlled warehouse facilities for VIP clients.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-chile-ambassador-factory-floor.jpg", eventType: "Facility Tour", date: "May 2023", location: "Qingdao Free Trade Zone", year: "2023" },
  { title: "Rare Bottle Archive Access", description: "Exclusive viewing of our rare and vintage spirit collections for select collectors.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-chile-ambassador-production-line.jpg", eventType: "Facility Tour", date: "April 2023", location: "Qingdao Free Trade Zone", year: "2023" },
  { title: "Climate-Controlled Storage Tour", description: "Specialized tour of our advanced storage facilities in Qingdao Free Trade Zone.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-chile-ambassador-qingdao-ftz-tour.jpg", eventType: "Facility Tour", date: "March 2023", location: "Qingdao Free Trade Zone", year: "2023" },
  { title: "Private Client Visit", description: "Personalized tour and tasting experience for discerning collectors and high-net-worth clients.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-chile-cellar-visit.jpg", eventType: "Facility Tour", date: "February 2023", location: "Qingdao Free Trade Zone", year: "2023" },
  { title: "Distributor Exclusive Tour", description: "Private tour designed for our international distributors to understand our quality control and logistics.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-international-delegation-production-line.jpg", eventType: "Facility Tour", date: "January 2023", location: "Qingdao Free Trade Zone", year: "2023" },
  { title: "Collector's Archive Preview", description: "An exclusive preview of upcoming additions to our rare spirits archive for serious collectors.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-international-delegation-suediane-exterior.jpg", eventType: "Facility Tour", date: "December 2022", location: "Manor Suedane, HK", year: "2022" },
  { title: "Wine Vault Experience", description: "Immersive tour of our climate-controlled wine vault, showcasing our most prized vintages.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-international-delegation-walking-campus.jpg", eventType: "Facility Tour", date: "November 2022", location: "Qingdao Free Trade Zone", year: "2022" },
  { title: "Whiskey Cellar Tour", description: "A deep dive into our whiskey aging process, featuring barrels from our oldest reserves.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/facility-tours/2023-winery-barrel-room.jpg", eventType: "Facility Tour", date: "October 2023", location: "Qingdao Free Trade Zone", year: "2023" },

  // Meetings
  { title: "Honney Conti Cask Selection", description: "Special meeting with producers to select premium casks for Honney Conti collection.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/chile-ambassador-meeting.jpg", eventType: "Meeting", date: "May 2025", location: "Hong Kong", year: "2025" },
  { title: "Corazón de Lolita Launch Planning", description: "Strategic meeting to plan the launch of Corazón de Lolita premium wine collection.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/chile-ambassador-welcome-meeting.jpg", eventType: "Meeting", date: "April 2025", location: "Hong Kong", year: "2025" },
  { title: "Business Strategy Meeting", description: "Key discussion with international partners on market expansion and product development.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/business-meeting-with-partners-.jpg", eventType: "Meeting", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "Sunny Land Private Tasting", description: "Exclusive tasting session for distributors featuring Sunny Land premium whiskey collection.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/chile-wine-promotion-meeting.jpg", eventType: "Meeting", date: "March 2025", location: "Hong Kong", year: "2025" },
  { title: "European Distributor Meeting", description: "Signing ceremony and strategy session with our European distribution partners.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/honney-conti-planet1-signing.jpg", eventType: "Meeting", date: "February 2025", location: "Hong Kong", year: "2025" },
  { title: "Asian Market Strategy", description: "Roundtable discussion focused on growth strategies for key Asian markets.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/international-partnership-discussion.jpg", eventType: "Meeting", date: "January 2025", location: "Hong Kong", year: "2025" },
  { title: "African Market Strategy", description: "Collaborative planning session to enter and develop premium spirits markets in Africa.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meeting-with-partners.jpg", eventType: "Meeting", date: "January 2025", location: "Hong Kong", year: "2025" },
  { title: "Producer Partnership Discussion", description: "Post-trade show review and partnership negotiation with potential new producers.", imageUrl: "https://www.unitedspiritshk.com/united-spirits-site/assets/img/meetings/trade-show-product-review.jpg", eventType: "Meeting", date: "December 2024", location: "Hong Kong", year: "2024" },
];

export default caseStudiesData;
